version: '3.9'
services:
  postgres:
    image: postgres:15
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    image: testtask:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL:       jdbc:postgresql://postgres:5432/user_db
      SPRING_DATASOURCE_USERNAME:  postgres
      SPRING_DATASOURCE_PASSWORD:  postgres
      SPRING_DATA_REDIS_HOST:      redis
      SPRING_DATA_REDIS_PORT:      6379
    depends_on:
      - postgres
      - redis
